stages:
- build
- cleanup_build
- test
- deploy
- cleanup
build_job:
  stage: build
  script:
  - mvn -B -U -Dmaven.test.skip=true -Dfile.encoding=UTF-8 -DsourceEncoding=UTF-8 clean install
  - mvn deploy
  only:
    - master
